<#
.SYNOPSIS
    Import Users, Groups, and Computers into the Target Domain.

.DESCRIPTION
    Reads transformed account data from the Transform directory and creates objects in the target domain.
    
    Phases:
    1. Create Groups (Empty)
    2. Create Users (with default password)
    3. Create Computers (Pre-stage)
    4. Populate Group Memberships

    Requires: Transformed CSVs generated by Transform-AccountMapping.ps1.
#>

[CmdletBinding(SupportsShouldProcess=$true)]
param(
    [Parameter(Mandatory = $false)]
    [string]$TargetDomain,

    [Parameter(Mandatory = $true)]
    [securestring]$DefaultPassword
)

# Import module and config
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$ModulePath = Join-Path (Join-Path (Split-Path -Parent (Split-Path -Parent $ScriptRoot)) 'Scripts') 'ADMigration\ADMigration.psd1'
if (-not (Test-Path $ModulePath)) { throw "Module manifest missing." }
Import-Module $ModulePath -Force
Write-Log -Message "Loaded ADMigration module from $ModulePath" -Level INFO
if (-not (Get-Command Invoke-Safely -ErrorAction SilentlyContinue)) { throw "Invoke-Safely unavailable" }

$config = Get-ADMigrationConfig
$TransformPath = Join-Path $config.TransformRoot 'Accounts'

if (-not (Test-Path $TransformPath)) {
    Write-Log -Message "Transform directory not found at $TransformPath. Run Transform-AccountMapping.ps1 first." -Level ERROR
    throw "Missing Transformed Account Data"
}

if (-not $TargetDomain) { $TargetDomain = (Get-ADDomain).DNSRoot }

Write-Log -Message "Starting Account Import to $TargetDomain..." -Level INFO

$SidMapping = [System.Collections.Generic.List[PSObject]]::new()

# Helper to find latest file
function Get-LatestFile ($pattern) {
    Get-ChildItem -Path $TransformPath -Filter $pattern | Sort-Object LastWriteTime -Descending | Select-Object -First 1
}

# 1. Import Groups
$groupFile = Get-LatestFile "Transformed_Groups_*.csv"
if ($groupFile) {
    Invoke-Safely -ScriptBlock {
        $groups = Import-Csv $groupFile.FullName
        foreach ($g in $groups) {
            if ($g.Action -eq "Migrate") {
                $params = @{
                    Name = $g.TargetName
                    SamAccountName = $g.TargetSam
                    Path = $g.TargetOU
                    GroupScope = $g.GroupScope
                    GroupCategory = $g.GroupCategory
                    Description = $g.Description
                    Server = $TargetDomain
                    OtherAttributes = @{ 'mail' = $g.Mail }
                }
                try {
                    $created = New-ADGroup @params -PassThru -ErrorAction Stop
                    if ($created) {
                        Write-Log -Message "Created Group: $($g.TargetName)" -Level INFO
                        $SidMapping.Add([PSCustomObject]@{
                            Type      = "Group"
                            SourceSam = $g.SamAccountName
                            TargetSam = $created.SamAccountName
                            SourceSID = $g.SID
                            TargetSID = $created.SID.Value
                        })
                    }
                } catch {
                    Write-Log -Message "Failed to create Group $($g.TargetName): $_" -Level WARN
                }
            }
        }
    } -Operation "Import Groups"
}

# 2. Import Users
$userFile = Get-LatestFile "Transformed_Users_*.csv"
if ($userFile) {
    Invoke-Safely -ScriptBlock {
        $users = Import-Csv $userFile.FullName
        foreach ($u in $users) {
            if ($u.Action -eq "Migrate") {
                $params = @{
                    Name = $u.TargetName
                    SamAccountName = $u.TargetSam
                    Path = $u.TargetOU
                    GivenName = $u.GivenName
                    Surname = $u.Surname
                    DisplayName = $u.DisplayName
                    AccountPassword = $DefaultPassword
                    Enabled = ($u.Enabled -eq 'True')
                    ChangePasswordAtLogon = $true
                    Description = $u.Description
                    Server = $TargetDomain
                    OtherAttributes = @{ 'mail' = $u.Mail }
                }
                try {
                    $created = New-ADUser @params -PassThru -ErrorAction Stop
                    if ($created) {
                        Write-Log -Message "Created User: $($u.TargetName)" -Level INFO
                        $SidMapping.Add([PSCustomObject]@{
                            Type      = "User"
                            SourceSam = $u.SamAccountName
                            TargetSam = $created.SamAccountName
                            SourceSID = $u.SID
                            TargetSID = $created.SID.Value
                        })
                    }
                } catch {
                    Write-Log -Message "Failed to create User $($u.TargetName): $_" -Level WARN
                }
            }
        }
    } -Operation "Import Users"
}

# 3. Import Computers
$compFile = Get-LatestFile "Transformed_Computers_*.csv"
if ($compFile) {
    Invoke-Safely -ScriptBlock {
        $comps = Import-Csv $compFile.FullName
        foreach ($c in $comps) {
            if ($c.Action -eq "Migrate") {
                $params = @{
                    Name = $c.TargetName
                    SamAccountName = $c.TargetSam
                    Path = $c.TargetOU
                    Description = $c.Description
                    Server = $TargetDomain
                }
                try {
                    $created = New-ADComputer @params -PassThru -ErrorAction Stop
                    if ($created) {
                        Write-Log -Message "Pre-staged Computer: $($c.TargetName)" -Level INFO
                        $SidMapping.Add([PSCustomObject]@{
                            Type      = "Computer"
                            SourceSam = $c.SamAccountName
                            TargetSam = $created.SamAccountName
                            SourceSID = $c.SID
                            TargetSID = $created.SID.Value
                        })
                    }
                } catch {
                    Write-Log -Message "Failed to create Computer $($c.TargetName): $_" -Level WARN
                }
            }
        }
    } -Operation "Import Computers"
}

# 4. Populate Memberships
$memberFile = Get-LatestFile "Transformed_Memberships_*.csv"
if ($memberFile) {
    Invoke-Safely -ScriptBlock {
        $memberships = Import-Csv $memberFile.FullName
        foreach ($row in $memberships) {
            try {
                # Assuming CSV has TargetGroupSam and TargetMemberSam
                if ($PSCmdlet.ShouldProcess($row.TargetGroupSam, "Add member $($row.TargetMemberSam)")) {
                    Add-ADGroupMember -Identity $row.TargetGroupSam -Members $row.TargetMemberSam -Server $TargetDomain -ErrorAction Stop
                    Write-Log -Message "Added $($row.TargetMemberSam) to $($row.TargetGroupSam)" -Level DEBUG
                }
            } catch {
                Write-Log -Message "Failed to add member $($row.TargetMemberSam) to $($row.TargetGroupSam): $_" -Level WARN
            }
        }
    } -Operation "Import Memberships"
}

# Export SID Mapping
$MapFile = Join-Path $config.TransformRoot 'Mapping' "Identity_Map_Final.csv"
$SidMapping | Export-Csv -Path $MapFile -NoTypeInformation
Write-Log -Message "Exported SID mapping to $MapFile" -Level INFO

Write-Host "----------------------------------------------------------------" -ForegroundColor Cyan
Write-Host "Account Import Complete"
Write-Host "Check logs for details."
Write-Host "----------------------------------------------------------------" -ForegroundColor Cyan